Hack to install openssl@1.1 and mysql-client@5.7

diff --git a/laptop b/laptop
--- a/laptop
+++ b/laptop
@@ -176,6 +176,48 @@ cask "slack"
 cask "sync"
 EOF
 
+# Hack Unsupported Taps
+# We still rely on a few brew packages that are now unsupported, and
+# need to hack their formulae to work.
+
+fancy_echo "Hacking unsupported brew Taps"
+
+brew tap homebrew/core --force
+
+hack_unsupported_tap_failed() {
+  echo "WARNING: unable to correct $1 formula"
+  echo "Please use 'brew edit $1' to correct the formula"
+  echo "(remove the 'disable! date:' line)"
+  exit 1
+}
+
+hack_unsupported_tap() {
+  # in the following command we might encounter .bak files that were not removed properly
+  # so we ensure the actual Formula file is the one we select
+  local formula
+  formula="$(find $HOMEBREW_PREFIX/Library/Taps -name "$1.*" | sort | head -1)"
+
+  if [ -f "$formula" ]; then
+    if sed -i '' '/disable! date:/d' "$formula"; then
+      echo "√ $1"
+    else
+      hack_unsupported_tap_failed "$1"
+    fi
+  else
+    hack_unsupported_tap_failed "$1"
+  fi
+}
+
+hack_unsupported_tap openssl@1.1
+hack_unsupported_tap mysql-client@5.7
+
+unset -f hack_unsupported_tap
+unset -f hack_unsupported_tap_failed
+
+# Install mysql-client@5.7
+HOMEBREW_NO_INSTALL_FROM_API=1 brew install mysql-client@5.7
+brew link --force mysql-client@5.7
+
 append_to_zshrc "eval \"\$(starship init zsh)\"" 1
 append_to_zshrc "eval \"\$(zoxide init zsh)\"" 1
 
